// Code generated by Padi Generator. DO NOT EDIT.
package base

import (
	"time"
)

type User struct {
	ID uint `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
	Email string `db:"email" json:"email"`
	Password string `db:"password" json:"password"`
	Role string `db:"role" json:"role"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	UpdatedAt *time.Time `db:"updated_at" json:"updated_at"`
}

func (User) TableName() string {
	return "users"
}
